Feature add news sabrine
Projektmodul/Intranet pull request #144
Opened 2021-02-06 15:17 UTC by sabrine-gamdou

Added functionalities:
- creating news (make sure you upload the image first)
- deleting news (only for admin)
- showing a complete news article
- changed database table pages_news (it doesn't have its proper primary key now, only a composite key (page_id + news_id)
- the newest news are shown first on the page

2021-02-06 15:23 UTC, sabrine-gamdou commented
News table:
```
CREATE TABLE news(
	news_id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	description VARCHAR NOT NULL,
	text TEXT NOT NULL,
	type VARCHAR(255) CHECK (type IN('Unternehmensnachricht', 'Centernachricht', 'Allgemeine Nachricht')),
	created_at TIMESTAMP NOT NULL,
	link_id INTEGER REFERENCES links (link_id),
	image_id INTEGER REFERENCES images (image_id),
	notification_id INTEGER REFERENCES notifications (notification_id)
); 
```

2021-02-06 15:23 UTC, sabrine-gamdou commented
pages_news table:
```
CREATE TABLE pages_news(
	page_id INTEGER NOT NULL REFERENCES pages (page_id),
	news_id INTEGER NOT NULL REFERENCES news (news_id)
);
```

2021-02-07 07:24 UTC, LauraNeu commented
Müssen die Create Befehle also noch abgeändert werden?

2021-02-07 16:27 UTC, anastasiya-jh commented
Öhm hier ist ein kleiner Rechtschreibfehler ^^

![image](https://user-images.githubusercontent.com/48677165/107152720-af644a00-6969-11eb-8f24-d0d7850c241d.png)

Es sollte heißen: nachfolgenden

2021-02-07 16:29 UTC, sabrine-gamdou commented
Ich habe das eigentlich von CareerView kopiert XD sollte es auch dort ändern ..

2021-02-07 16:31 UTC, anastasiya-jh commented
Oh ups xD

2021-02-07 18:06 UTC, anastasiya-jh requested changes
![image](https://user-images.githubusercontent.com/48677165/107155188-45eb3800-6977-11eb-9166-064e31244859.png)
Nachdem ich eine Nachricht hier lösche aktualisiert es nicht direkt. Kannst du die GUI einmal reloaden lassen, sobald eine Nachricht gelöscht wurde? Man muss aktuell erst die Seite wechseln bevor man sieht dass die Nachricht nicht mehr da ist ^^

2021-02-07 18:09 UTC, sabrine-gamdou commented
Man muss es manuell aktualisieren, sonst kann man die Nachricht: erfolgreich gelöscht, nicht sehen

2021-02-07 18:14 UTC, anastasiya-jh commented
Ahh oki, dann lassen wir das so

2021-02-07 18:22 UTC, anastasiya-jh approved these changes
Thanks for the work! Def looks much better now :')

2021-02-07 18:23 UTC, merged