Commentfix ideamanagement jessica
Projektmodul/Intranet pull request #155
Opened 2021-02-10 14:47 UTC by JessicaReistel

In IdeasManagementView Beschreibung der Methode initializeGrid() geändert

2021-02-11 11:26 UTC, anastasiya-jh commented on src/main/java/com/example/application/ui/horizontal/community/IdeasManagementView.java
> + *  @lastUpdated 10.02.2021 by Jessica Reistel
When adding only comments you don't need to change the lastUpdated :') just leave it as it is

2021-02-11 11:28 UTC, anastasiya-jh requested changes
The last two method-comments are no Java doc comments, please change that

2021-02-12 13:11 UTC, JessicaReistel commented
Hab's geändert :)

2021-02-13 17:37 UTC, vskowronsky approved these changes
Dankeschön :-)

2021-02-13 17:38 UTC, merged