Jpa entites und repositories
Projektmodul/Intranet pull request #35
Opened 2021-01-05 18:58 UTC by sabrine-gamdou

Die Entitäten und ihre Beziehungen werden nun auf die Datenbanktabellen abgebildet. 
Die Repositories sind für die CRUD-Operationen, da eine explizite Implementierung der Queries, ist in diesem Fall nicht nötig, das übernehmen die Repositories, es sei denn, wir brauchen etwas Besonderes)

Die Konstruktoren sind nicht in allen Entitätsklassen zu finden. 
Dies wird in einem nächsten PullRequest erledigt.
Der Code bezüglich der NotificationsView ist vorübergehend auskommentiert, die Implementierung muss aktualisiert und über einen Service mit der Datenbank verbunden werden. bitte nicht löschen für jetzt.

2021-01-05 19:05 UTC, sabrine-gamdou commented
Es ist eine Menge auf einmal, aber es musste so schnell wie möglich erledigt werden, damit wir Zeit für die anderen Backend-Aufgaben haben. 

Eine weitere Erklärung folgt nächste Woche, außerdem wird das, was gemacht wurde, dokumentiert und zu oneNote hinzugefügt.

Hinweis: Dies könnte sich ändern, wenn sich das Datenbankmodell ändern würde, um die Anforderungen an die Rollen/Berechtigungen zu erfüllen

2021-01-05 19:10 UTC, sabrine-gamdou commented
Die JPA Facet muss in IntellIj hinzugefügt werden, damit dies funktioniert.
![image](https://user-images.githubusercontent.com/47325924/103688240-ce9a4100-4f91-11eb-956a-fb76039f0149.png)

Auch die persistence data source
![image](https://user-images.githubusercontent.com/47325924/103688314-effb2d00-4f91-11eb-96f8-98b013f2ea83.png)

2021-01-05 21:11 UTC, vskowronsky approved these changes

2021-01-06 12:41 UTC, anastasiya-jh requested changes
Momentan ist der Code nur funktionsfähig in einer lokalen Datenbank. Remote kann dafür noch nicht genutzt werden.  In der application.properties müssen die Daten immer hardcodiert mit nutzername + pw eingetippt werden. Bitte einmal mit Variablen ersetzen und wir erstellen eine Anleitung, wie wir die Variablen erstellen.

2021-01-06 13:10 UTC, anastasiya-jh approved these changes
Thank you! Now it works perfectly fine.

2021-01-06 13:11 UTC, merged