Einfügen der zugeteilten PageIds und auslesen des titels und contents von den horizontalen und inProgress
Projektmodul/Intranet pull request #83
Opened 2021-01-24 15:12 UTC by MoMa666

…Datenbank von MainView und InProgressView und  von den horizontalen Seiten bis auf Ideenmanagement und BlackBoard.

2021-01-24 16:05 UTC, vskowronsky commented on src/main/java/com/example/application/ui/horizontal/community/CommunityView.java
> +        pageEntity = pageService.findPageById(11);
Hier ist eine falsche ID angegeben. Es wird "Projekte" ausgelesen. 
![image](https://user-images.githubusercontent.com/49377845/105636009-5626f180-5e66-11eb-9fbe-aab941d25a90.png)

2021-01-24 16:11 UTC, vskowronsky commented on src/main/java/com/example/application/ui/horizontal/ourCompany/AboutUsView.java
> -    }
Dieser Code bleibt in der Klasse drin. Wird zwar nicht aus der DB gelesen, aber zum Zeigen bleibt er erstmal da.

2021-01-24 16:14 UTC, vskowronsky requested changes
Bitte einmal die ID ändern und bei AboutUsView den Code wieder mit reinnehmen

2021-01-24 16:16 UTC, MoMa666 commented on src/main/java/com/example/application/ui/horizontal/community/CommunityView.java
> +        pageEntity = pageService.findPageById(11);
Ja da muss die 18rein komisch warum er das nicht kopiert hat

2021-01-25 01:18 UTC, MoMa666 commented
Der Fehler wurde hier behoben und müsste mit den Änderungen in 91cefe8 & c27f7a1 behoben sein. Es läuft jetzt ohne Probleme

2021-01-25 15:33 UTC, vskowronsky approved these changes

2021-01-25 15:43 UTC, merged